name: Notification on Workflow Failure

on: 
  workflow_run:
    workflows: ["Your Workflow Name"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ failure() }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send notification
      uses: softprops/action-gh-release@v1
      with:
        files: ''
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
